### ISSUE TITLE
TopoRender.vue里的Cookies设置是不是有问题

### ISSUE THREAD

**Issue by sissi144** [xubaobao19940428/Web_topo#2]
this.application = Cookies.get('application') ？   这是什么 Cookies设置里有定义application吗

报错 Error in mounted hook: "TypeError: Cannot read property 'match' of undefined"

**Comment by xubaobao19940428** [comment]
这个报错不死Cookies的报错，能截图吗

**Comment by gtb514753** [comment]
> 这个报错不死Cookies的报错，能截图吗

的确不是cookie的报错，是它下一行的报错。点击预览之后的报错。
![image](https://user-images.githubusercontent.com/52941500/126134148-2d133453-f122-4157-8867-65f9034dd23e.png)
![image](https://user-images.githubusercontent.com/52941500/126134360-d62f3807-d71a-45a3-8e9f-dbcea2cce986.png)
